version: '3.3'

services:
  sfr-api:
    build: ./sfr-api
    ports:
      - "3000:3000"
    volumes:
      - ./sfr-api:/usr/src/app
      - /usr/src/app/node_modules #exclude this folder in the volume
    env_file:
      - ./sfr-api/.env

  sfr-ui:
    build: ./sfr-ui
    ports:
      - "5000:3000"
    volumes:
      - ./sfr-ui:/usr/src/app
      - /usr/src/app/node_modules #exclude this folder in the volume
    environment:
      NODE_ENV: production
      REACT_APP_API: localhost:3000
    command: node scripts/start.js

  # sfr-db:
  #   build: ./sfr-db
  #   ports:
  #     - "1433:1433"
  #   depends_on:
  #     - sfr-api
  #   volumes:
  #     - "mssqldata:/var/opt/mssql/data:rw"
  #   env_file:
  #     - ./sfr-db/.env

# volumes:
#   mssqldata: