version: '3.7'

services:
  sfr-db:
    build: ./sfr-db
    ports:
      - "1433:1433"
    volumes:
      - "mssqldata:/var/opt/mssql/data:rw"
    env_file:
      - ./sfr-db/.env

  sfr-api:
    build: ./sfr-api
    ports:
      - "3000-3002:3000"
    depends_on:
      - sfr-db
    volumes:
      - ./sfr-api:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./sfr-api/.env

  sfr-ui:
    build: ./sfr-ui
    ports:
      - "80:3000"
    volumes:
      - ./sfr-ui:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production

volumes:
  mssqldata: