FROM node:8.14

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

EXPOSE 3000

COPY . .

CMD REACT_APP_API=localhost:3000 PORT=3000 node scripts/start.js
